### ISSUE TITLE
How to use 

### ISSUE THREAD

**Issue by TonyDMorris** [BlueHuskyStudios/BHBezelNotification#4]
Hi I'm trying to use your bhbezels package but I'm new to swift, do I have to use it as a git submodule? As when I try to import through package manager it says there is no modules exported or something similar?

**Comment by KyNorthstar** [comment]
Thanks for the poke!

This was created before Swift Packages existed, so yes it must be used as a submodule for now.

It really should be a Swift Package, though! I'll put that on my to-do list; thank you!

---

As for your question about how to use it in its current state, assuming you're using an `.xcodeproj` or `.xcworkspace` file:





- Add this as a Git Submodule to your project
- Right-click your desired group or folder reference (or a file inside that) in Xcode's sidebar, and select "Add Files to “My Project Name”…"
  <img width="300" alt="CleanShot 2023-06-26 at 15 06 46@2x" src="https://github.com/BlueHuskyStudios/BHBezelNotification/assets/10189808/1b0645cc-8fca-4632-96f0-fe4988a39330">
    - Uncheck "Copy items if needed"
       <img width="304" alt="CleanShot 2023-06-26 at 15 07 03@2x" src="https://github.com/BlueHuskyStudios/BHBezelNotification/assets/10189808/a48f505d-d847-4bd8-89c8-1909dedcc199">
    - Select the following:
        - `./BHBezelNotification/BHBezelNotification.swift`
        - Everything under `./BHBezelNotification/Extensions/` 
    - Make sure they will be included in every target where you'll be displaying the bezels
       <img width="292" alt="CleanShot 2023-06-26 at 15 11 34@2x" src="https://github.com/BlueHuskyStudios/BHBezelNotification/assets/10189808/656e1c99-ac55-49a4-a005-a5e34096fb97">
- And now they're compiled as part of your project! See [the instructions in the README](https://github.com/BlueHuskyStudios/BHBezelNotification#usage) for further info on how to use this

**Comment by TonyDMorris** [comment]
thats awesome thanks for taking the time to get back to me
